### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by debrajhyper**

### CODE REVIEW

**Comment by eshanvohra** [comment]
Doing for hacktoberferst?

**Comment by debrajhyper** [comment]
Yes 👍

**Comment by eshanvohra** [comment]
Then first merge my pull request on your repo COVID-19-TRACKER-INDIA

**Comment by debrajhyper** [comment]
you mean fork?

**Comment by eshanvohra** [comment]
yes the repo that u have forked from Tsahai28/COVID-19-TRACKER-INDIA this repo i have made a pull request pls merge it first.

**Comment by debrajhyper** [comment]
done

**Comment by eshanvohra** [comment]
done great!

**Comment by debrajhyper** [comment]
did you accept my pull request?

**Comment by eshanvohra** [comment]
yes bro

**Comment by debrajhyper** [comment]
Thans man 😇

**Pull request merged**
